/**
 * Decodes the compact account reference generated by the Webazi websites
 * (webaziairtime.vercel.app, webaziairtimehub.vercel.app) back into
 * {network, amount, phone}. This is the counterpart of buildAccountRef()
 * in each site's submitOrder().
 *
 * Format (10 chars, fits Safaricom's 12-char STK AccountReference limit):
 *   [1] network prefix   S = Safaricom, A = Airtel
 *   [3] airtime amount   KES, base36, zero-padded (covers up to 46,655)
 *   [6] phone number     last 9 digits (leading 0 dropped), base36,
 *                        zero-padded (covers up to ~2.17 billion)
 *
 * This is what's actually deliverable — the amount is the 100% airtime
 * value, not whatever was discounted/paid, so delivery never has to trust
 * the paid amount shown elsewhere in the SMS.
 */

import { normalizeToLocal } from './phone';

export type DecodedRef = {
  network: 'safaricom' | 'airtel';
  amount: number;
  phone: string; // local format, e.g. 0735830024
};

const REF_PATTERN = /^([SA])([0-9A-Z]{3})([0-9A-Z]{6})$/;

export function decodeAccountRef(ref: string): DecodedRef | null {
  const match = ref.trim().toUpperCase().match(REF_PATTERN);
  if (!match) return null;

  const [, prefix, amtCode, numCode] = match;
  const amount = parseInt(amtCode, 36);
  const numDigits = parseInt(numCode, 36).toString().padStart(9, '0');

  if (!Number.isFinite(amount) || amount <= 0) return null;
  if (numDigits.length !== 9) return null;

  return {
    network: prefix === 'A' ? 'airtel' : 'safaricom',
    amount,
    phone: '0' + numDigits,
  };
}

function toBase36(num: number, width: number): string {
  return num.toString(36).toUpperCase().padStart(width, '0');
}

/**
 * Inverse of decodeAccountRef() above — builds the same compact ref the
 * Webazi websites generate. Kept in this file, right next to the
 * decoder, so the two can never drift out of sync with each other.
 *
 * `amountKes` is always the FULL airtime amount to be delivered (100%),
 * not whatever gets discounted/charged at STK time — that split (e.g.
 * the 5% agent discount in app/customer-payment.tsx) is entirely the
 * caller's concern. This function only knows how to pack
 * {network, amount, phone} into 10 chars.
 */
export function buildAccountRef(network: 'safaricom' | 'airtel', amountKes: number, phone: string): string {
  const prefix = network === 'airtel' ? 'A' : 'S';
  const digits9 = phone.replace(/^0/, '').slice(-9).padStart(9, '0');
  const amtCode = toBase36(Math.round(amountKes), 3);
  const numCode = toBase36(parseInt(digits9, 10), 6);
  return `${prefix}${amtCode}${numCode}`;
}

/**
 * Pulls the "for account XXXXXXXXXX" reference out of an M-PESA
 * confirmation SMS. Returns null if the SMS has no account reference
 * (e.g. it's not a till/paybill payment at all).
 */
export function extractAccountRef(smsBody: string): string | null {
  const match = smsBody.match(/for account\s+([A-Za-z0-9]+)/i);
  return match ? match[1] : null;
}

export type DecodedPaybill = {
  network: 'safaricom' | 'airtel';
  amount: number;
  phone: string; // local format, e.g. 0729914983
  ref: string; // e.g. "S0729914983" — for display/logging alongside the receipt
};

const PAYBILL_ACCOUNT_PATTERN = /Account Number\s+([SA])\s*(\d{9,10})/i;
const PAYBILL_AMOUNT_PATTERN = /Ksh\s*([\d,]+(?:\.\d+)?)\s+received/i;

/**
 * Decodes a manual Paybill payment confirmation SMS — the shape you get
 * when a customer pays your Paybill directly and types their own phone
 * number into the Account Number field, prefixed with S (Safaricom) or
 * A (Airtel) so we know which network to dial from:
 *
 *   "UHQO43V4WF Confirmed. on 26/8/26 at 4:09 PM Ksh100.00 received from
 *    JOAB IRUNGU NDEGO 254729914983. Account Number S0729914983 New
 *    Utility balance is Ksh100.00"
 *
 * This is structurally different from decodeAccountRef() above: there's
 * no compact generated ref, just a raw phone number and the paid amount
 * stated directly in the SMS. Returns null if either piece is missing
 * or unparseable — callers should fall back to the "unmatched" bucket.
 */
export function decodePaybillSms(smsBody: string): DecodedPaybill | null {
  const acctMatch = smsBody.match(PAYBILL_ACCOUNT_PATTERN);
  if (!acctMatch) return null;

  const [, prefix, rawNumber] = acctMatch;
  const phone = normalizeToLocal(rawNumber);
  if (!phone) return null;

  const amtMatch = smsBody.match(PAYBILL_AMOUNT_PATTERN);
  if (!amtMatch) return null;

  const amount = Math.round(parseFloat(amtMatch[1].replace(/,/g, '')));
  if (!Number.isFinite(amount) || amount <= 0) return null;

  return {
    network: prefix.toUpperCase() === 'A' ? 'airtel' : 'safaricom',
    amount,
    phone,
    ref: `${prefix.toUpperCase()}${rawNumber.replace(/\D/g, '')}`,
  };
}

/**
 * Pulls the M-PESA receipt code from the start of a confirmation SMS
 * (e.g. "UHOO43KO9X Confirmed. You have received..."). Purely for
 * display/reconciliation — not used for decoding.
 */
export function extractReceipt(smsBody: string): string | null {
  const match = smsBody.trim().match(/^([A-Z0-9]{8,12})\s+Confirmed/i);
  return match ? match[1].toUpperCase() : null;
}

/**
 * Builds the AccountReference used for the app's own M-Pesa STK
 * subscription payments (services/subscription.ts's paySubscriptionViaStk),
 * as opposed to a customer airtime order's compact buildAccountRef()
 * code above.
 *
 * Format: "SB" + the paying agent's own local phone number, e.g.
 *   SB0729914983
 * "SB" = Subscription (never collides with the single-letter S/A
 * network prefixes used elsewhere: decodeAccountRef()'s REF_PATTERN
 * only matches an exact 10-char string, and decodePaybillSms()'s
 * PAYBILL_ACCOUNT_PATTERN only matches a single S/A letter — a 2-letter
 * "SB" prefix matches neither, so a subscription payment can never be
 * mistaken for an airtime order and trigger an accidental delivery).
 * "pn" = the paying number itself, purely so the developer can identify
 * which agent a given subscription payment belongs to from the M-Pesa
 * statement/SMS — this reference is never decoded back into a delivery
 * job, it's for reconciliation only.
 */
export function buildSubscriptionAccountRef(payingPhone: string): string {
  const digits = payingPhone.replace(/\D/g, '');
  const local = digits.startsWith('254') ? '0' + digits.slice(3) : digits.startsWith('0') ? digits : '0' + digits;
  return `SB${local}`;
}

/**
 * Normalizes a local (0...) phone number to 2547.../2541....
 * @deprecated USSD dialing now uses local format directly (see services/phone.ts
 * and sambaza.ts) — kept only so nothing that still imports this breaks.
 */
export function toMsisdn(localPhone: string): string {
  if (localPhone.startsWith('0')) return '254' + localPhone.slice(1);
  return localPhone;
}
